In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df_train = pd.read_csv ("train.csv")
df_test = pd.read_csv ("test.csv")

In [3]:
df_train.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [4]:
df_test.head(3)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q

In [5]:
# Describir brevemente la cantidad de valores faltantes para cada una de las variables de la base de datos.
print ("--- valores faltantes en train ----")
print(df_train.isnull().sum()[df_train.isnull().sum()>0])
print ("--- valores faltantes en test ---")
print(df_test.isnull().sum()[df_test.isnull().sum()>0])

--- valores faltantes en train ----
Age         177
Cabin       687
Embarked      2
dtype: int64
--- valores faltantes en test ---
Age       86
Fare       1
Cabin    327
dtype: int64

In [6]:
#Completar aquellas variables que se encuentran faltantes para las bases de train (“Age”,”fare”, “Cabin”) y test ( “Age”, “Cabin”, “embarked”).

mean_age_train = df_train['Age'].mean()
print (f" -- rellenado 'Age' con el el promedio {mean_age_train:.2f}")
mean_age_test =df_test['Age'].mean()
print (f"-- rellenado 'Age' con el promedio {mean_age_test:.2f}")
df_train['Age'] = df_train['Age'].fillna(mean_age_train)
df_test['Age'] = df_test['Age'].fillna(mean_age_test)

 -- rellenado 'Age' con el el promedio 29.70
-- rellenado 'Age' con el promedio 30.27

In [7]:
mean_fare_train = df_train['Fare'].mean()
print (f" -- rellenado 'Fare' con el el promedio {mean_fare_train:.2f}")
mean_fare_test =df_test['Fare'].mean()
print (f"-- rellenado 'Fare' con el promedio {mean_fare_test:.2f}")
df_train['Fare'] = df_train['Fare'].fillna(mean_fare_train)
df_test['Fare'] = df_test['Fare'].fillna(mean_fare_test)

 -- rellenado 'Fare' con el el promedio 32.20
-- rellenado 'Fare' con el promedio 35.63

In [8]:
mode_embarked_train = df_train["Embarked"].mode()[0]
print (f" -- rellenado de 'Embarked' con la moda: {mode_embarked_train}")
df_train['Embarked'] = df_train['Embarked'].fillna(mode_embarked_train)

 -- rellenado de 'Embarked' con la moda: S

In [9]:
total_files_train = len(df_train)
nulos_cabin_train =df_train ['Cabin'].isnull().sum()
porcentaje_train = (nulos_cabin_train / total_files_train) * 100
print(f"porcentaje de 'Cabin' faltante en train.csv: {porcentaje_train:.2f}%")

total_files_test = len(df_test)
nulos_cabin_test =df_test ['Cabin'].isnull().sum()
porcentaje_test = (nulos_cabin_test / total_files_test) * 100
print(f"porcentaje de 'Cabin' faltante en test.csv: {porcentaje_test:.2f}%")

porcentaje de 'Cabin' faltante en train.csv: 77.10%
porcentaje de 'Cabin' faltante en test.csv: 78.23%

In [10]:
print("-- Eliminado de columna 'Cabin' por porcentaje alto de datos faltantes")
df_train = df_train.drop('Cabin', axis=1)
df_test = df_test.drop('Cabin', axis=1)

-- Eliminado de columna 'Cabin' por porcentaje alto de datos faltantes

In [11]:
df_train['Sex'] =df_train['Sex'].map ({'male':0, 'female':1})
df_test['Sex'] =df_test['Sex'].map ({'male':0, 'female':1})

In [13]:
df_train = pd.get_dummies(df_train, columns=['Embarked'])
df_test = pd.get_dummies(df_test, columns=['Embarked'])

In [14]:
df_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [15]:
df_test.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [16]:
#Ajustar el primer modelo de regresión logística
features_to_drop = ['PassengerId','Name','Ticket']
df_train_processed = df_train.drop(features_to_drop, axis=1)
df_test_processed = df_test.drop(features_to_drop, axis=1)

In [17]:
#Ajustar el primer modelo de regresión logística
print ("Ajuste de modelo de regresion")
x = df_train_processed.drop("Survived", axis=1)
y= df_train_processed['Survived']

Ajuste de modelo de regresion

In [18]:
x_train,X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=28)
print (f'Datos de entrenamiento divididos: {len(x_train)} para entrenar, {len(X_test)} para probar.')

Datos de entrenamiento divididos: 712 para entrenar, 179 para probar.

In [19]:
model = LogisticRegression(max_iter=2000)

In [20]:
model.fit(x_train, y_train)
print ('Modelo entrenado exitosamente')

Modelo entrenado exitosamente

In [21]:
#Entrenar y determinar el nivel de accuracy del primer modelo.

In [23]:
print ("--Punto D nivel de Acurracy del modelo -- ")
y_pred = model.predict(X_test)
y_pred

--Punto D nivel de Acurracy del modelo --

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0])

In [24]:
accuracy = accuracy_score(y_test, y_pred)
print(f"El nivel de accuracy (precision) del modelo es: {accuracy * 100:.2f}%")
print(f"(esto signidica que el modelo acerto el {accuracy * 100:.2f}% de las veces que se prueba)")

El nivel de accuracy (precision) del modelo es: 79.33%
(esto signidica que el modelo acerto el 79.33% de las veces que se prueba)